import { auth, db } from './firebase.js';
import { signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { collection, getDocs } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import { renderShell, statCard, postCard, adminEmail } from './ui.js';

onAuthStateChanged(auth, async(user)=>{ if(!user || user.email!==adminEmail){ alert('Bạn không phải admin!'); location.href='index.html'; return; } renderShell('admin', user); await renderAdmin(); });
async function renderAdmin(){ let posts=[]; try{ const snap=await getDocs(collection(db,'posts')); posts=snap.docs.map(d=>({id:d.id,...d.data()})); }catch(e){ console.warn(e); }
  document.getElementById('mainContent').innerHTML = `<section class="admin-layout"><aside class="admin-sidebar"><h2>Admin</h2><a>Dashboard</a><a>Bài viết</a><a>Người dùng</a><a>Báo cáo</a><button id="logoutBtn">Đăng xuất</button></aside><div class="admin-main"><section class="page-head"><span class="eyebrow">Quản trị</span><h1>Dashboard thống kê</h1></section><div class="stats-grid">${statCard('Người dùng','--','👥')}${statCard('Bài viết',posts.length,'📰')}${statCard('Bài chờ duyệt',0,'⏳')}${statCard('Đã đăng',posts.length,'✅')}${statCard('Từ chối',0,'🚫')}${statCard('Đã gỡ',0,'📦')}</div><div class="chart-card"><span style="height:55%"></span><span style="height:70%"></span><span style="height:40%"></span><span style="height:85%"></span><span style="height:60%"></span></div><h2>Duyệt bài</h2><div class="post-grid">${posts.map(postCard).join('') || '<p>Chưa có bài viết.</p>'}</div><div class="table-card"><h2>Hoạt động gần đây</h2><p>Duyệt • Yêu cầu sửa • Từ chối • Gỡ bài</p></div></div></section>`; document.getElementById('logoutBtn').onclick=async()=>{ await signOut(auth); location.href='index.html'; };
}
